name: Code Review Assistant

permissions:
  pull-requests: write
  issues: write

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 radon bandit snyk

      # Step 4: Run Static Analysis (Pylint)
      - name: Run Pylint Analysis
        run: |
          pylint **/*.py --output-format=json > pylint_output.json || true

      # Step 5: Run Static Analysis (Flake8)
      - name: Run Flake8 Analysis
        run: |
          flake8 **/*.py --format='%(path)s:%(row)d:%(col)d: %(code)s %(text)s' > flake8_output.txt || true

      # Step 6: Measure Cyclomatic Complexity and Maintainability
      - name: Run Cyclomatic Complexity Analysis
        run: |
          radon cc **/*.py -s -j > radon_complexity_output.json || true
          radon mi **/*.py -j > radon_maintainability_output.json || true

      # Step 7: Run Bandit Security Analysis
      - name: Run Bandit Security Analysis
        run: |
          bandit -r . -f json -o bandit_output.json || true

      # Step 8: Run Snyk Security Scan
      - name: Run Snyk Dependency Scan
        run: snyk test --json > snyk_output.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 9: Generate Feedback
      - name: Generate Feedback
        run: |
          python - <<EOF > feedback.md
          import json

          # Initialize feedback
          feedback = "## Code Review Feedback\\n"

          # Pylint feedback
          feedback += "\\n### 1. Static Analysis Feedback (Pylint)\\n"
          try:
              with open('pylint_output.json', 'r') as f:
                  pylint_issues = json.load(f)
                  if pylint_issues:
                      for issue in pylint_issues:
                          feedback += (
                              f"- **{issue['path']}** (Line {issue['line']}, Column {issue['column']}): "
                              f"{issue['message']} [{issue['symbol']}]\n"
                          )
                      feedback += "\n**Suggestions:**\n"
                      feedback += "- Address the reported issues by following PEP-8 and Python coding guidelines.\n"
                  else:
                      feedback += "No issues detected.\n"
          except Exception as e:
              feedback += f"Error processing Pylint results: {str(e)}\\n"

          # Flake8 feedback
          feedback += "\\n### 2. Static Analysis Feedback (Flake8)\\n"
          try:
              with open('flake8_output.txt', 'r') as f:
                  flake8_issues = f.readlines()
                  if flake8_issues:
                      for issue in flake8_issues:
                          feedback += f"- {issue.strip()}\\n"
                      feedback += "\n**Suggestions:**\n"
                      feedback += "- Fix unused imports, indentation errors, and other PEP-8 violations.\n"
                  else:
                      feedback += "No issues detected.\n"
          except Exception as e:
              feedback += f"Error processing Flake8 results: {str(e)}\\n"

          # Radon complexity feedback
          feedback += "\\n### 3. Cyclomatic Complexity Feedback\\n"
          try:
              with open('radon_complexity_output.json', 'r') as f:
                  radon_issues = json.load(f)
                  for file, issues in radon_issues.items():
                      for issue in issues:
                          feedback += (
                              f"- **{file}**: Function `{issue['name']}` at line {issue['lineno']} "
                              f"has complexity {issue['complexity']}.\n"
                          )
                  feedback += "\n**Suggestions:**\n"
                  feedback += "- Refactor complex functions into smaller, reusable components.\n"
          except Exception as e:
              feedback += f"Error processing Radon complexity results: {str(e)}\\n"

          # Radon maintainability feedback
          feedback += "\\n### 4. Maintainability Index Feedback\\n"
          try:
              with open('radon_maintainability_output.json', 'r') as f:
                  radon_issues = json.load(f)
                  for file, score in radon_issues.items():
                      feedback += f"- **{file}**: Maintainability Index = {score}\\n"
              feedback += "\n**Suggestions:**\n"
              feedback += "- Improve maintainability by reducing complexity and following clean code principles.\\n"
          except Exception as e:
              feedback += f"Error processing Radon maintainability results: {str(e)}\\n"

          # Bandit feedback
          feedback += "\\n### 5. Security Analysis Feedback (Bandit)\\n"
          try:
              with open('bandit_output.json', 'r') as f:
                  bandit_issues = json.load(f).get('results', [])
                  for issue in bandit_issues:
                      feedback += (
                          f"- **{issue['filename']}** (Line {issue['line_number']}): {issue['issue_text']} "
                          f"[Severity: {issue['issue_severity']}, Confidence: {issue['issue_confidence']}]\n"
                      )
              if not bandit_issues:
                  feedback += "No security issues found by Bandit.\\n"
          except Exception as e:
              feedback += f"Error processing Bandit results: {str(e)}\\n"

          # Snyk feedback
          feedback += "\\n### 6. Dependency Security Scan (Snyk)\\n"
          try:
              with open('snyk_output.json', 'r') as f:
                  snyk_issues = json.load(f).get('vulnerabilities', [])
                  for vuln in snyk_issues:
                      feedback += (
                          f"- **{vuln['package']}** ({vuln['version']}): {vuln['title']} "
                          f"[Severity: {vuln['severity']}]\n"
                      )
              if not snyk_issues:
                  feedback += "No vulnerabilities found by Snyk.\\n"
          except Exception as e:
              feedback += f"Error processing Snyk results: {str(e)}\\n"

          # Save feedback to file
          with open('feedback.md', 'w') as f:
              f.write(feedback)
          EOF

      # Step 10: Post Feedback as a Pull Request Comment
      - name: Post Feedback
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const feedback = fs.readFileSync('feedback.md', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: feedback
            });
