name: Code Review Workflow

permissions:
  pull-requests: write
  issues: write

on:
  pull_request:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 radon

    - name: Run Code Analysis
      run: |
        pylint **/*.py > pylint_output.txt || true
        flake8 **/*.py > flake8_output.txt || true
        radon cc -s -a **/*.py > radon_output.txt || true

    - name: Set up GitHub CLI
      run: sudo apt-get install -y gh

    - name: Post Feedback
      run: |
        echo "### Static Analysis Feedback:" > comment_body.txt
        echo '```plaintext' >> comment_body.txt
        cat pylint_output.txt >> comment_body.txt
        echo '```' >> comment_body.txt
        echo "### Cyclomatic Complexity (Radon) Feedback:" >> comment_body.txt
        echo '```plaintext' >> comment_body.txt
        cat radon_output.txt >> comment_body.txt
        echo '```' >> comment_body.txt

        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat comment_body.txt)"
