name: Code Analysis

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint joblib

    - name: Run Code Assistant
      run: python code_assistant.py

    - name: Comment on Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const feedback = JSON.parse(fs.readFileSync('feedback.json', 'utf8'));
          for (const [file, comments] of Object.entries(feedback)) {
            for (const comment of comments) {
              github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.payload.pull_request.number,
                body: `File: ${file}\nComment: ${comment}`,
              });
            }
          }
