name: Code Review

permissions:
  pull-requests: write
  issues: write

on:
  pull_request:
    paths:
      - '**/*.py'  # adjust based on your language (e.g., '*.js' for JS)
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Install necessary dependencies
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust as per your project

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 scikit-learn

      # Step 2: Run static analysis
      - name: Run Static Analysis (flake8)
        id: flake8
        run: |
          flake8 . --max-line-length=88 --output-file=flake8_report.txt
          cat flake8_report.txt  # Display the results

      # Step 3: Load ML Model and run pattern recognition
      - name: Run Pattern Recognition using ML model
        id: pattern_recognition
        run: |
          python analyze_code.py  # This script will load the model and run the analysis

      # Step 4: Combine static analysis and ML feedback
      - name: Combine Feedback and generate results
        id: generate_feedback
        run: |
          python generate_feedback.py  # Script to combine feedback from both tools and generate final report

      # Step 5: Upload the feedback report as an artifact
      - name: Upload Feedback Artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-review-feedback
          path: feedback_report.txt  # Adjust based on your output

