name: Python CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure all dependencies from requirements.txt are installed
        pip install scikit-learn  # Install scikit-learn if it's not in requirements.txt

    - name: Run code assistant
      run: |
        python code_assistant.py  # Run your script 

    - name: Comment on Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const feedback = JSON.parse(fs.readFileSync('feedback.json', 'utf8'));
          for (const [file, comments] of Object.entries(feedback)) {
            for (const comment of comments) {
              github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.payload.pull_request.number,
                body: `File: ${file}\nComment: ${comment}`,
              });
            }
          }
